In [5]:
import numpy as np

# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

## HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [39]:
def vander(arr, increasing=False):
    N = len(x)
    if increasing == True: 
        return np.column_stack([x**i for i in range(N)])
    else: 
        return np.column_stack([x**(N-i-1) for i in range(N)])


In [40]:
x = np.array([1, 2, 3, 5])
my_result = vander(x)
library_result = np.vander(x)
print(my_result) 
print(library_result)
print(np.equal(my_result, library_result))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [42]:
x = np.array([1, 2, 3, 5])
my_result = vander(x, increasing=True)
library_result = np.vander(x, increasing=True)
print(my_result) 
print(library_result)
print(np.equal(my_result, library_result))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10  
===== == == == == == == == == == ==  
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4  
y2 35 = (20+30+40+50)/4  
y3 45 = (30+40+50+60)/4  
y4 55 = (40+50+60+70)/4  
y5 65 = (50+60+70+80)/4  
y6 75 = (60+70+80+90)/4  
y7 85 = (70+80+90+100)/4  
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [3]:
def simple_moving_average(vector, window_size = 2):
    result = np.cumsum(vector, dtype=float)
    result[window_size:] = result[window_size:] - result[:-window_size]
    return result[window_size - 1:] / window_size 
        

In [4]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3
print(simple_moving_average(arr, 3))

[   5.            4.66666667    5.66666667    6.66666667    9.66666667
   28.66666667   49.33333333   72.66666667   84.           93.33333333
  116.33333333]
